### ISSUE TITLE
PHPCS & PHPDoc difference on @package tag?

### ISSUE THREAD

**Issue by eidng8** [phpDocumentor/phpDocumentor#1508]
I'm using PHP_CodeSniffer and PHPDoc, and got an frustrating issue:
phpcs requires the package tag to present in every file and class doc block. While phpdoc allows only one package tag per file.

Which one to follow?

Opened an issue on PEAR too, links here for convenience: http://pear.php.net/bugs/bug.php?id=20477

**Comment by mvriel** [comment]
phpDocumentor should have no issue with an `@package` in both the file and class docblock; you are not allowed to use the package tag multiple times within the same docblock.

There is an open issue because an error is emitted that the package tag may not be provided multiple times; is this also what you experience?

**Comment by eidng8** [comment]
Yes, it seems to be the root cause of the issue I've met

**Comment by dajoho** [comment]
I'm having this problem too. I like the PEAR CS and don't really want to chance to PSR2. Is there any way we can instruct phpdoc to just ignore everything to do with "@package"?

**Comment by jaapio** [comment]
This bug was reported on phpDocumentor v2, and will not be addressed. If this is still applicable on the latest version. Please feel free to open a new issue.
