### ISSUE TITLE
No file links for global functions and constants in "clean" template

### ISSUE THREAD

**Issue by jack126guy** [phpDocumentor/phpDocumentor#1716]
In the sidebar there are headings that say "File" but no actual link accompanying them.

In the case of namespace functions and constants outside a class, there aren't even "File" headings at all (but there are "Inherited from" headings...).

May be related to #1298?

[Test file](http://gist.github.com/jack126guy/8d5566babc556cb096ba)

**Comment by WoodrowShigeru** [comment]
I've also noticed some things about this:

* The file exists in docs/files/ but is just not linked.
* The link to the file appears on the sidebar of the file-page and links to itself, while being needed and missing in the global-space-page.
* The author tag is listed in the sidebar of that file-page instead of the global-space-page. I'm under the impression that it should be inherited from the file DocBlock to all underlying DocBlocks (classes, functions, etc.)
* [my example file](https://pastebin.com/jJaN0H7F)

**Comment by jaapio** [comment]
Support for the clean template has been dropped. Everyone is advised to move the the new default template.
