### ISSUE TITLE
Is "/blabla" a placeholder for development version?

### ISSUE THREAD

**Issue by huzhenghui** [phpDocumentor/phpDocumentor#1867]
Maybe this is a junk question, but I am confused. The code is:

https://github.com/phpDocumentor/phpDocumentor2/blob/develop/data/templates/zend/index.xsl#L29
`
<xsl:template match="/blabla">
`
I can't find any source code match this.

**Comment by jaapio** [comment]
I had to search in the history of this file but I think the xsl:template is not used since it will never have a match. All xsl templates are based on the abstract template. So the index from that template is used. 
However I'm not 100% sure about this and if this was fully implemented.

Are you looking for anything specific?

**Comment by jaapio** [comment]
Closing since we are deprecating this template
