### ISSUE TITLE
phpDocumentor.ERROR: Uncaught Exception Error: "Undefined class constant 'VERSION'" 

### ISSUE THREAD

**Issue by neoacevedo** [phpDocumentor/phpDocumentor#1972]
running `phpDocumentor.phar self-update`
## Expected Behavior
running update for phpDocumentor.phar and update the Phar file

## Actual Behavior
Error.
```
phpDocumentor.ERROR: Uncaught Exception Error: "Undefined class constant 'VERSION'" at phar:///home/nestor/bin/phpDocumentor.phar/src/phpDocumentor/Command/Phar/UpdateCommand.php line 74 {"exception":"[object] (Error(code: 0): Undefined class constant 'VERSION' at phar:///home/nestor/bin/phpDocumentor.phar/src/phpDocumentor/Command/Phar/UpdateCommand.php:74)"}
```
## Steps to Reproduce the Problem
Not needed, only running phpDocumentor.phar with self-update parameter

## Your environment

* Version used: 3.0.0-alpha1
* Install method **phar**
* php version 7.2.4
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): openSUSE Tumbleweed

**Comment by jaapio** [comment]
Thanks for reaching out.

We were planning to introduce some kind of rolling release. But since that didn't come to a reality we decided to remove the self-update command again. It was introduced in the alpha stage. But we think we have better alternatives now like [phive](phar.io) and a docker image on docker hub. 

If both not fit your needs you will have to download phpDocumentor from the releases page of this project. Maybe we will come up with some kind of installer in the future. But for now we will keep the 2 mentioned installation methods.
