### ISSUE TITLE
Generating docs from multiple directories always uses only one

### ISSUE THREAD

**Issue by horgh** [phpDocumentor/phpDocumentor#2070]
## Expected Behavior

I have two related projects, and I want to include docs generated from both in one run. (Two directories)

## Actual Behavior

I only get docs from only one directory.

## Steps to Reproduce the Problem

`php /will/bin/phpDocumentor2/build/phpDocumentor.phar -d src,../MaxMind-DB-Reader-php/src --cache-folder=mycache -t doc-test`

I also tried using a config - same result. Config:

```xml
<?xml version="1.0" encoding="UTF-8" ?>                                                                                                                                              
<phpdocumentor>
  <files>
    <directory>src</directory>
    <directory>../MaxMind-DB-Reader-php/src</directory>
  </files>
</phpdocumentor>
```

## Your environment

* Version used: 0b8425e3bdd00f1f9a08054d28576d36a39d5835
* Install method: 'make' to build the .phar
* php version: 7.2.15-0ubuntu0.18.10.1
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Ubuntu 18.10
* Link to your project: https://github.com/maxmind/GeoIP2-php (and trying to include https://github.com/maxmind/MaxMind-DB-Reader-php)

**Comment by jaapio** [comment]
At the moment phpdocumentor only supports one root directory. As a work around I think you should be able to run phpdocumentor from the common root directory of both projects.

**Comment by jaapio** [comment]
Hi @horgh,

You would help us a lot when you are able to give the nightly builds a try.
https://github.com/phpDocumentor/phpDocumentor#nightly-builds

we did change a lot in the path handling. So your setup could work. 
As in phpDoc v2 paths are relative to the current working directory, but indifference we do only support 1 root directory. at the moment. More about this is explained in #2159 

So running phpdocumentor in a directory like this: `/opt/phpdoc/src/phpDocumentor/Parser$ ../../../bin/phpdoc --env=dev -d . -d ../Pipeline/` will not work currently.
What phpdocumentor will do is get the first path as "project root". but since `../Pipeline` is breaking out of this root it will fail to find the directory. However when you pass a config file:

```
<?xml version="1.0" encoding="UTF-8" ?>                                                                                                                                              
<phpdocumentor>
  <files>
    <directory>./Parser</directory>
    <directory>./Pipeline</directory>
  </files>
</phpdocumentor> 
``` 
Then execute `/opt/phpdoc/src/phpDocumentor/Parser$ ../../../bin/phpdoc --config=../config.xml` it will work. 

Please let us know if this fixes your issue. We will keep you posted about the progress of multiple root directory support.

**Comment by horgh** [comment]
I tested just now using [this build](https://github.com/phpDocumentor/phpDocumentor/commit/7fb864764347634fa97e366188fdd942d49ae0f3/checks?check_suite_id=397109791). It worked great! Thank you for the great instructions and for making this work. Awesome!
