### ISSUE TITLE
Source view is not exact position

### ISSUE THREAD

**Issue by somratcste** [phpDocumentor/phpDocumentor#2086]
When I click source view,, It just open the file from the top, it doesn't go to the exact method. 
Like I want to show the source for checcustomerEmailExists(), it's not redirect me to this method. It just open the source from the top. 
![1](https://user-images.githubusercontent.com/4497856/56791331-1a7d7480-6807-11e9-90a7-75d319a51cef.PNG)

## Expected Behavior

I want to show the file source view go to the method position. 
![3](https://user-images.githubusercontent.com/4497856/56791291-fb7ee280-6806-11e9-8c9e-80a72cbaa924.PNG)

## Actual Behavior

It just open the file from the starting. 
![2](https://user-images.githubusercontent.com/4497856/56791316-13566680-6807-11e9-9620-fe5b9527f14a.PNG)
## Steps to Reproduce the Problem

  1. Just Create any method documentation 
  2. Click the source view 
  3. See it doesn't redirect you the exact position. 

## Your environment
Zend Framework v1.12.20
php 7.0 
Windows 10

**Comment by mvriel** [comment]
This is a restriction we are aware of. The source code is included as is on a file basis and adding anchor would require adding additional complexity. Although the feature would be nice I must admit that we currently rank breaking issues and releasing phpDocumentor 3 higher on the priority ladder.

I sincerely hope a contribution will help to speed up this request but until then I am afraid it can take a while for this improvement to be implemented

**Comment by dev-masta** [comment]
I suggest, since jQuery is already used and we know the methods name, it would be easy to write a small onClick function that scrolls to the appropriate code line after the modal is opened.
Even though it would need to search the content of the code, it will still be precise and fast enough without using anchors.

**Comment by jaapio** [comment]
Sounds good to me. Feel free to provide a PR with this solution.

**Comment by dev-masta** [comment]
I will gladly do it, but could use some further directions.
Which branch to check out, and are there any special guidelines I should be aware of?

**Comment by dev-masta** [comment]
@jaapio I actually did this, and not only that - I took the entire `clean` template and have created a new, `clean-dark` template.
The new template is much nicer and has several minor things fixed/added, like the left sidebar fixed (not being collapsed on every page load) and Markers and Errors pages having the files on their list sorted by folders.

In order to do that, I had to introduce a new Twig filter which I didn't know where to put so I've put it in `\vendor\phpdocumentor\phpdocumentor\src\phpDocumentor\Plugin\Twig\Extension.php`.
I got that folder because I installed phpdocs via composer.

Now, I tried to fork the develop branch and create a new PR, but there is no Plugin folder in that branch and I'm kinda lost about what and how it's supposed to be done.

Any help appreciated :)

**Comment by jaapio** [comment]
We removed the support for plugins in phpdocumentor v3. You can find the twig extension https://github.com/phpDocumentor/phpDocumentor2/blob/develop/src/phpDocumentor/Transformer/Writer/Twig/Extension.php

Please create the pr and we will see how we can merge this. Since you didn't change any existing template I'm not sure how this will fit into the project. With all new features that are introduced in phpdoc v3, it might be possible that we merge al features of the different templates into a single new version. So it will take more time than usual to merge your pr.

**Comment by jaapio** [comment]
I fixed this for the new default template in phpdoc v3. Which is the preferred template for phpDocumentor right now. 

The old clean template will still have this bug. But I think it is not worth our time to support multiple templates. Especially because time is limited. And our new template will contain all new features, while the older templates like clean won't have these.
