### ISSUE TITLE
Class document does not show trait methods

### ISSUE THREAD

**Issue by ve3** [phpDocumentor/phpDocumentor#2098]
When generate the document it was shown the methods from traits in phpDocumentor 2.x but not in 3.x

## Expected Behavior

Expect to see trait methods in the class document page.
For example, this class **https://github.com/Rundiz/simple-cache/blob/version3/src/Drivers/Apcu.php** use this trait **https://github.com/Rundiz/simple-cache/blob/version3/src/Drivers/MultipleTrait.php**
The `deleteMultiple()` and any other methods in this trait should appears in the Apcu class document.

## Actual Behavior

The trait methods does not showing.

## Steps to Reproduce the Problem

  1. Open command prompt.
  2. Run `phpDocumentor.phar --directory="src" --cache-folder="../../_cache" --target="../../_doc-simple-cache" --title="SimpleCache" --force`.

## Your environment

* Version used: 3.0.0-alpha3
* Using phpDocumentor.phar and its pubkey.
* PHP 7.1.26
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Windows 10 x64
* I'm trying to generate doc from this project. https://github.com/Rundiz/simple-cache

**Comment by mvriel** [comment]
Since this issue was opened we have severely invested in improving phpDocumentor, including a new template. I have just run your project and indeed, now the trait methods are included.

Please note that you may need to use one the phpDocumentor.phar in one of our builds to get the same results. We plan on releasing a beta soon
