### ISSUE TITLE
@method tag not parsed into final document

### ISSUE THREAD

**Issue by dartanian300** [phpDocumentor/phpDocumentor#2100]
## Expected Behavior

When specifying several @method tags in a class docblock, the methods will display in the output documentation.

## Actual Behavior

Only one method is displayed (it's not the first one) and the rest are somehow appended to that method's description or title (depending on template). This issue is occurring on all templates. Do I have something wrong? I've tried various spacing and formats.
<img width="549" alt="Screen Shot 2019-07-12 at 4 01 09 PM" src="https://user-images.githubusercontent.com/3358537/61155200-492df180-a4be-11e9-9f24-db765b31638f.png">
<img width="805" alt="Screen Shot 2019-07-12 at 4 01 31 PM" src="https://user-images.githubusercontent.com/3358537/61155220-56e37700-a4be-11e9-8cbc-44282aaebd04.png">

## Your environment

* Version used: 2.9.0
* Install method: Composer
* php version: 7.1.23
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): MacOS Mojave

**Comment by jaapio** [comment]
This looks like a bug. But since all our efforts go to phpdoc v3, I must admit that this will not have priority right now. 
phpDoc v2 is not fully compatible with php 7.0+ so it works like it does now. We cannot upgrade the code base without a lot of work. Which is done in phpdoc v3, which is currently in an alpha stage.

**Comment by jaapio** [comment]
This bug was reported on phpDocumentor v2, and will not be addressed. If this is still applicable on the latest version. Please feel free to open a new issue.
