### ISSUE TITLE
@var self resolving to elf

### ISSUE THREAD

**Issue by soyuka** [phpDocumentor/phpDocumentor#2212]
## Expected Behavior
Expecting the behavior I read in https://github.com/phpDocumentor/phpDocumentor/issues/544 

## Actual Behavior

Type fqdn is `elf`.

Origin issue: https://github.com/api-platform/core/issues/3344
Reproduction repo: https://github.com/soyuka/self-referencing-metadata-api-platform 
Tracked to https://github.com/symfony/symfony/blob/5e394c40f05228231b4ce3aeff99e3a01b424e03/src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php#L93

## Steps to Reproduce the Problem

Just use `@var self`.

**Comment by jaapio** [comment]
I reproduced the issue using your reproduction repo. But it seems that our `DocblockFactory` and `TypeResolver` are never executed. 

I'm going to dig a bit deeper into this issue, but I don't expect it to be an issue on our side at the moment.

**Comment by jaapio** [comment]
The example only works when I remove my `var/cache` dir. 

I will keep you posted.

**Comment by jaapio** [comment]
I think I got a location where this error is comming from: 
https://github.com/symfony/symfony/blob/5e394c40f05228231b4ce3aeff99e3a01b424e03/src/Symfony/Component/PropertyInfo/Util/PhpDocTypeHelper.php#L157

The input of the method is a type object `Self_` from our `TypeResolver`  Which is converted by `getPhpTypeAndClass` to `elf` 

I don't know how to fix this, but it looks like the results of the `TypeResolver` are not interpreted correctly. It could be that this is caused by an undetected breaking change on our side. I didn't investigate that. But as far as I'm concerned now the `TypeResolver` didn't have a breaking change. It might have been a breaking change between DocBlockReflection 2 and v3....

If you need any help from our side please contact us again. But for now, I think this issue can be closed. Because our libraries are working as expected. 

```
object(phpDocumentor\Reflection\Types\Self_)#1122 (0) {
}
string(4) "self"
string(6) "object"
```
