### ISSUE TITLE
Support (or documentation) for docblock templates

### ISSUE THREAD

**Issue by johnpancoast** [phpDocumentor/phpDocumentor#2225]
# Feature request
In v1 of PHPDoc it was possible to use one docblock to document many "elements" (constants, members, etc) with the following docblock syntax:

```
    /**#@+
     * This comment applies to each in the block
     *
     * @var string HTTP method constants
     */
    public const METHOD_HEAD = 'HEAD';
    public const METHOD_GET = 'GET';
    public const METHOD_POST = 'POST';
    // etc
```

These were called [Templates](https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_phpDocumentor.howto.pkg.html#basics.docblocktemplate) in v1 and the above block would act as-if you had documented each element separately.

I cannot find anything in the v2 documentation about this behavior. And confusingly, in v2 there is another concept called "templates" that are about the output of the docs, i.e., the template of the output which has nothing to do with this old feature.

Does the above original template functionality still exist and if so, where is it documented in v2? Is there a plan to add this functionality?

**Comment by mvriel** [comment]
Hi John,

This is a long, open feature request for phpDocumentor 2 (https://github.com/phpDocumentor/phpDocumentor/issues/42). I can definitely say that it won't be added to phpDocumentor 2 but I cannot exclude it will be added in a release of phpDocumentor 3.

To be open and honest, it is not on a backlog. There is not much demand for this feature and it is complex to implement since it requires special care when parsing a file. If it will be implemented, the Reflection library of phpDocumentor is the location to do so.

I would like to ask you to leave a comment or upvote in the original feature request (https://github.com/phpDocumentor/phpDocumentor/issues/42) as that gives us an indication of how much people value it but for now, I am afraid I will have to close this one.

Thank you for submitting this request

**Comment by johnpancoast** [comment]
Hi @mvriel, thanks. I assumed there was probably an open issue for this since v2's been around awhile but I couldn't find it by searching "template" since the unrelated template issues were coming up. I admittedly only did a quick search though.

Anyway, thanks for your quick reply and explanation. I don't think the feature is _that_ crucial, but it is definitely a nice-to-have, especially for classes that have many similar members or constants. I updated that task. Thank you!
