### ISSUE TITLE
Fatal Error: failed to open stream: CURRENT_DIR/vendor/phpdocumentor/phpdocumentor/src/config/bundles.php

### ISSUE THREAD

**Issue by LeonardoCor** [phpDocumentor/phpDocumentor#2277]
phpDocumentor, installed via composer, reports a require() fatal error relative to Fatal Error: failed to open stream: CURRENT_DIR/vendor/phpdocumentor/phpdocumentor/src/config/bundles.php file. In fact, the config dir, inside the src dir in the above path, doesn't exists.

## Expected Behavior
The right path should be identified.

## Actual Behavior
Documentation is not generated.

## Steps to Reproduce the Problem

  1. install phpDocumentor via composer, every version 3 or above
  2. run phpdoc locally from within CURRENT_DIR

## Your environment
* Version used: 3.0.0-beta
* Install method: composer
* php version: 7.3.3
* Operating system and version: 
![Immagine](https://user-images.githubusercontent.com/46627003/74083695-697b5a00-4a67-11ea-96fd-f421a462928a.png)
Windows 8.1

**Comment by mvriel** [comment]
The `getProjectDir()` method by Symfony's `HttpKernel/Kernel` class returns the wrong folder (there is an extra 'src' in there that is not supposed to be there). I am able to replicate the issue, but weirdly enough the flow does not behave as I would anticipate so it takes some time to find the cause.

**Comment by mvriel** [comment]
When phpDocumentor is installed using Composer, the project directory as
detected by Symfony is in the wrong folder. Instead of picking the
actual root, it picks the `src` folder underneath.
    
By overriding the getProjectDir method, the algorithm used in
http-kernel's Kernel class does function correctly and the issue no
longer arises.

Please do be aware that we offer limited support on installing phpDocumentor using Composer; we have plans to change how this installation method works by installing a PHAR distribution instead of the source.

In the past, there have been too many issues with conflicting packages; something we are unable to support.

**Comment by LeonardoCor** [comment]
Solved in v3.0.0-rc. Thanks.
