### ISSUE TITLE
Unresolved class as string

### ISSUE THREAD

**Issue by orklah** [phpDocumentor/phpDocumentor#2298]
Hi,

Working on PRs for static analysis, I stumbled onto something not optimal.

When a class is not resolved, it can be stored as a string (in ClassDescriptor::parent for example). I'm not sure where it happens, but it definitely do.

This is problematic for static analysis (for example, it's not possible to type hint "object" because of that).

I'd like to change this behaviour and create a new class "UnresolvedClassDescriptor" or something like that that could replace the string.

I'm not sure if it's a relevant change, but it would be definitely a BC break at some level.

Is this something worth pursuing?

**Comment by jaapio** [comment]
Hi @orklah 

This is definitely something we should address. But it will require some redesign of the descriptors which I would like to delay until we have v3 released officially. BC breaks are not really a thing in phpdocumentor, since this is an application and people should not extend the application. It is never designed to do that.

Redesigning the descriptors requires some understanding about the internals of phpDocumentor. We are creating a reflection of the project under work, these reflections are created per file. So they do not contain any relations. All the code to do this is in `phpDocumentor/Reflection`. The classes for example are not linked to parent classes for example. The relation is a `Fqsen` object after the reflection is finished. We call this the parsing phase. The result of this phase is fully cachable because there are no bi-directional or circular relations.

From these reflection objects are the descriptors build by the assembler. This is building a set of descriptors with the string values as you detected during the static analysis improvements. Also this result is cached. There are still no relations between the objects of classes, interfaces ect. 

Second step in generating the docs is done by our `Compiler`. Which is building the namespace tree using the `NamespaceDescriptor`. As part of the compile phase we are also executing the `Linker` which is linking the `ClassDescriptor`s and `InterfaceDescriptor`s to there containing namespace and replacing the strings in the `ClassDescriptor`s with the actual parent `ClassDescriptor`. This result is not cached. Since it will contain a lot of bi-directional relations. Objects in this form cannot be serialized. The bi-directional relations are simplifying the rendering a lot. 

Changing the descriptors will impact the phases I described. But might also impact the rending process since you might need to change the interface of the descriptors. All of this can be done. But it will require a lot of testing since not all of our functionality is covered by unit tests or e2e tests. 

If you are interested to help us we would appreciate this very much. But not just before a final release of phpDocumentor :-). You might agree with me that we need to think about this a bit more than just starting to replace some strings. It would be very nice if we could get there without breaking the current templates.

**Comment by orklah** [comment]
Thanks for the detailed answer!

I didn't think it was such a big work. From working with the project, I'm starting to have an idea of what the objects are, but I don't have a clue about how they interact yet :)

I'll continue working on static improvement, hoping this will make refactors easier later then!
