### ISSUE TITLE
Question: PHPDoc tag usage related

### ISSUE THREAD

**Issue by moliata** [phpDocumentor/phpDocumentor#2320]
Hey!
Sorry for using GitHub issue as a way of communication, but couldn't find a better place for these questions.

1. Do tags declared in the file-level docblock apply to every single structural element in that file? Does that also mean class methods, properties as well?
2. How `@version` tag should be used? Should it be used to show the user which version of the project this file belongs to? If so, should it be placed in file-level docblock? I don't find the documentation's description understandable, sorry!
3. Speaking of `@author` and `@copyright` tag, where they should be placed? If there is a single author and a single copyright, should it be placed in class-level or file-level docblock?

Best regards,
Ben.

**Comment by jaapio** [comment]
Hi Ben,

1. No file-level docblock is used to add a license to the file in most cases. You can add any tag or description you want, but that will not affect the other elements like classes and properties. The only inheritance of docblocks is applied when a class extends another class.

2. The version tag is used to version elements, this can be done on a file level, which indicates the version of a file. But can also be applied to elements. In some projects, it is used to tell when a certain element was introduced. But that's the behavior of the `@since` tag. 

3. The `@author` and `@copyright` tags can be placed on any element. Depending on who you want to provide the copyright of that element. If it is a method with a certain clever solution you might want to add it to that method.

**Comment by moliata** [comment]
Thanks so much for the response!
So to ensure me, 2 more questions 😅.

1. Should `@version` tag be used to show the project's version? Should we change the `@version` tag if the file itself was not modified but other files in the same project were?
2. So assuming there is a single author that has written the entire file and therefore meaning that the entire file is subject to the single copyright holder, to not repeat myself, I should put `@author` and `@copyright`  tags in the file-level docblock. Right?

**Comment by jaapio** [comment]
1. The version tag describes the version of the element. So when you add on a file level it could be the version of that specific file. To make it more clear what the version represents you can add a description. But that's up to you. The version tag doesn't standardize the usage of the tag itself. So in many cases a description will be needed.

2. If a file is written by one or more authors that need to be mentioned you can add multiple author tags at file level. But also, in this case, it is up to you how to use the tag in your project. The tag itself is standardized, but how to use it in a project is up to you in your project.
