### ISSUE TITLE
Inline @see and @link tags not working

### ISSUE THREAD

**Issue by thebigb** [phpDocumentor/phpDocumentor#2321]
Documentation for `@see` mentions that it can be used inline: https://docs.phpdoc.org/latest/references/phpdoc/inline-tags/see.html

## Expected Behavior

Some kind of replacement for inline `{@see}` or `{@link}` tags.

## Actual Behavior

![image](https://user-images.githubusercontent.com/2717179/77213182-361df780-6b0a-11ea-9e34-1b089a434258.png)

## Steps to Reproduce the Problem

  1. Use `{@see MyClass}` or `{@link MyMethod()}` in any docblock

## Your environment

* Version used: https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.0.0-rc/phpDocumentor.phar
* Install method: RC release phar
* php version: 7.4
* Link to project: https://gitlab.com/1of0/php/ip-utils

**Comment by piczak** [comment]
hello, when this bug will be solved?

**Comment by jaapio** [comment]
Thanks for reaching out to us. I had to check this myself as well, and the latest phar contains an issue when rendering the inline tags in some cases. however, in your example, you added the inline tags in the summary of your docblock. 
As described in our reference docs, summaries are plaintext. They cannot contain any inline tags. 
https://docs.phpdoc.org/3.0/references/phpdoc/basic-syntax.html#summary

The description of your class can contain inline tags. So for example:

```
/** 
 * Summary goes here
 * 
 * This is a description containing an inline tag {@link https://docs.phpdoc.org/3.0/references/phpdoc/basic-syntax.html#summary} 
*/
```

I hope this makes it more clear for you. Please feel free to comment on this issue when you have any questions regarding this particular case. Otherwise, you can always create a new issue.
