### ISSUE TITLE
v3.0.0-rc: German Umlauts in source files cause: «An error was detected: Invalid "utf-8" string.»

### ISSUE THREAD

**Issue by oliveratgithub** [phpDocumentor/phpDocumentor#2336]
## Expected Behavior
When parsing a source file, formatted as proper utf-8, but still containing special characters like German umlauts in the PHP code*, should not throw a parsing error but read the file and contents properly.

Here's a PHP example with German umlauts:

```
<?php
if (!isset($frm)) $error = "Ungültiger Typ";
```

* note: the special character is part of the actual code, not the phpDoc blocks, description or another tag.

## Actual Behavior
Multiple files from my source code are ignored while parsing with an utf-8 related error message:

```
ALERT     [app]   Unable to parse file "www/actions/poll_edit.php", an error was detected: Invalid "utf-8" string.
ALERT     [app]   Unable to parse file "www/actions/stockbroker.php", an error was detected: Invalid "utf-8" string.
ALERT     [app]   Unable to parse file "www/actions/stockbroker.php", an error was detected: Invalid "utf-8" string.
ALERT     [app]   Unable to parse file "www/actions/tauschboerse.php", an error was detected: Invalid "utf-8" string.
ALERT     [app]   Unable to parse file "www/actions/tauschboerse.php", an error was detected: Invalid "utf-8" string.
ALERT     [app]   Unable to parse file "www/actions/tpleditor.php", an error was detected: Invalid "utf-8" string.
ALERT     [app]   Unable to parse file "www/actions/tpleditor.php", an error was detected: Invalid "utf-8" string.
…
```

## Steps to Reproduce the Problem

  1. Add an utf-8 encoded PHP file to your source code directory
  2. Add special characters like German umlauts within actual code (not phpDocu comments or tags!): e.g. `ä`, `ö`, `ü`
  2. Run the phpDocumentor PHAR using `php ./phpDocumentor.phar -t ~/Documents/phpdocu -d ~/Sites/www`
  3. Check the parsing output to see that the PHP file containing German umlaut has been raising an ALERT during the parsing process

## Your environment

* Version used: v3.0.0-rc
* Install method: phpDocumentor.phar
* php version: PHP 7.3.11 (cli) (built: Apr  3 2020 08:00:20) ( NTS )
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): macOS 10.15.5 Beta (19F62f)
* Link to your project: [zorgch/zorg-code/tree/upgrade-php-7.x](https://github.com/zorgch/zorg-code/tree/upgrade-php-7.x)

**Comment by mvriel** [comment]
Hello Oliver,

Encodings are problematic when a different one than UTF-8 is used. Even auto-detecting this is something that doesn't work all that well. For this reason, we introduced the `--encoding` flag (and accompanying configuration option).

I have looked at `poll_edit.php` in your project and noticed that the encoding that was used is ISO-8859-1 and not UTF-8.

My method of verification was that I downloaded the file using get (`wget https://raw.githubusercontent.com/zorgch/zorg-code/upgrade-php-7.x/www/actions/poll_edit.php`) and opened it in PHPStorm. PHPStorm tried to open the file as UTF-8 and all special characters were boxed question marks; when I requested PHPStorm to reopen the file as ISO-8859-1 all characters were properly displayed.

As a second opinion, I used Linux' file command and it also detected the file's contents as ISO-8859-1:

```
file poll_edit.php 
poll_edit.php: PHP script, ISO-8859 text
```

Since it would seem that there is not an issue at play here I will be closing this issue. If you disagree or have extra information that would show otherwise, please attach it to this issue and I will reopen it

**Comment by oliveratgithub** [comment]
@mvriel thanks for your analysis, explanation - and yes, the issue seems to be on my end (or my code) therefore absolutely Ok to close this.

and apologies, I checked my file for proper UTF-8 encoding before posting this, but it seems my IDE gave me wrong indication which let me to suggest it to be related to the German inline characters. My bad.

**Comment by mvriel** [comment]
No problem, encoding is hard. I have been bitten by encodings multiple times before so I totally get the confusion
