### ISSUE TITLE
Question: List of @author and their related code possible?

### ISSUE THREAD

**Issue by oliveratgithub** [phpDocumentor/phpDocumentor#2353]
If I remember correctly in phpDocumentor 2 there was a template which provided a page of all `@author` names linked to the items (docBlocks) each author was tagged to.

Is this still available in phpDocumentor 3 and if yes, can you point me to a default template showcasing this behavior? Or with what Twig instructions this could be achieved, similar to the Errors, Markers & Deprecation listings?

**Comment by jaapio** [comment]
I don't know all templates of v2 but v3 doesn't have such a list. our clean template has a list of tags, but since we are not using the author tag in our code it is not in the demo. A list of authors should be kind of easy to add. However, you might need to dig into the format of the descriptor which is not nicely documented yet. I will try to give you some handouts to see if you can get it done.

The line below gives you all elements with an author tag. 

`{% set elementsWithAuthor = project.indexes.elements|filter(element => element.author) %}`

Elements can be anything implementing `phpDocumentor\Descriptor\DescriptorAbstract`  

You might want to look: https://docs.phpdoc.org/3.0/getting-started/changing-the-look-and-feel.html#customizing-the-look-and-feel  for some more information about templates.

Let me know when you need more help or have some additional questions about templates. That will help me to update the docs about this subject.
