### ISSUE TITLE
`@author` support is missing in default

### ISSUE THREAD

**Issue by jaapio** [phpDocumentor/phpDocumentor#2446]
Template default is missing support for `@author` tags.

//cc @jrfnl

**Comment by jrfnl** [comment]
@jaapio I've ran some tests and I think this issue should be closed.

The tag itself is supported and works fine when used for classes/constants/properties/methods etc.

I think the issue is more that support for file docblocks and namespace docblocks, which are more typically the places were this tag is used, does not seem to be implemented in the template yet.

I will open a separate issue for that.

**Comment by mvriel** [comment]
Thanks for checking that. I must have forgotten to add a tags section to the file. Namespaces don't have DocBlocks because there is no authoritative declaration that we can use. Bit of a problem with namespaces as they are decentralized entities :(

**Comment by jrfnl** [comment]
> Namespaces don't have DocBlocks because there is no authoritative declaration that we can use. Bit of a problem with namespaces as they are decentralized entities :(

Yes, I was wondering about that. It kind of felt out of place to see "namespaces" listed in the structural elements list.

**Comment by mvriel** [comment]
Technically, it is a structural element as it is part of the element hierarchy. But it is a special case because it is decentralised. As well as that it can have a naming conflict with classes
