### ISSUE TITLE
@copyright support in default template

### ISSUE THREAD

**Issue by jaapio** [phpDocumentor/phpDocumentor#2447]
`@copyright` support in default template is missing

cc @jrfnl

**Comment by jrfnl** [comment]
@jaapio I've ran some tests and I think this issue should be closed.

The tag itself is supported and works fine when used for classes/constants/properties/methods etc.

I think the issue is more that support for file docblocks and namespace docblocks, which are more typically the places were this tag is used, does not seem to be implemented in the template yet.

I will open a separate issue for that.

**Comment by mvriel** [comment]
Thanks for checking that. I must have forgotten to add a tags section to the file. Namespaces don't have DocBlocks because there is no authoritative declaration that we can use. Bit of a problem with namespaces as they are decentralized entities :(
