### ISSUE TITLE
Fatal error when running phpdocumentor

### ISSUE THREAD

**Issue by russ3ell** [phpDocumentor/phpDocumentor#2516]
I hhave just installed phpdocumentor using phar with the command from a home directory on linux Centos 7
php phpDocumentor.phar -d . -t docs/api

I copied the docs/api data to a website I have on the server and the documentation looks as though it is displaying correctly.

However when I run 
./phpDocumentor-2.9.1/bin/phpdoc -d <website> -t <output dir>

I get the error below.  I am totally new to phpdocumentor so I might have installed it incorrectly. I made sure that Graphviz is installed.

Please can someone help

Fatal error: Uncaught RuntimeException: phpDocumentor expected to find an autoloader at "/home/<user>/phpDocumentor-2.9.1/src/phpDocumentor/../../vendor/autoload.php" but it was not there. Usually this is because the "composer install" command has not been ran yet. If this is not the case, please open an issue at http://github.com/phpDocumentor/phpDocumentor2 detailing what installation method you used, which path is mentioned in this error message and any other relevant information. in /home/<user>/phpDocumentor-2.9.1/src/phpDocumentor/Bootstrap.php:101
Stack trace:
#0 /home/<user>/phpDocumentor-2.9.1/src/phpDocumentor/Bootstrap.php(60): phpDocumentor\Bootstrap->createAutoloader('/home/<user>...')
#1 /home/<user>/phpDocumentor-2.9.1/bin/phpdoc(23): phpDocumentor\Bootstrap->initialize()
#2 {main}
  thrown in /home/<user>/phpDocumentor-2.9.1/src/phpDocumentor/Bootstrap.php on line 101

**Comment by jaapio** [comment]
Hi @russ3ell 

Welcome to the phpDocumentor project! It is good to hear that you have installed phpDocumentor to generate documentation for your project.

phpDocumentor has a number of ways to install the tool. The first and prefered one is using the phar file like you did in your first step. I think you tried to install phpDocumentor from source on the second command? Because I'm not sure how you actually did this I cannot give you the exact correct anwer to your question. But seen the error you get you need to run `composer install` in the directory `./phpDocumentor-2.9.1` if you are not familiar with composer I would recommend you to have a look at there website. https://getcomposer.org/ 

However if you are not familiar with composer, it might be hard to get started on this track. It there a specific reason why you want to install phpDocumentor from source?

**Comment by russ3ell** [comment]
The install documentation indicated that I should avoid using composer. I have now installed it and it all works. Thanks for all your help
