### ISSUE TITLE
clarification of the intended behavior of @internal

### ISSUE THREAD

**Issue by terrafrost** [phpDocumentor/phpDocumentor#2736]
There's `@internal` and `{@internal}`. I have a PR for my project (https://github.com/phpseclib/phpseclib/pull/1549) wherein it's being claimed that these two tags behave differently from one another. Quoting the PR:

> **@internal** is about mark method as internal of project and **{@internal}** Include a note in the Description that would only show in Developer Docs

Nothing in https://docs.phpdoc.org/latest/guide/references/phpdoc/tags/internal.html convinces me that that is the case.

Can y'all confirm which interpretation is correct?

Also, quoting the PR, "_if you use an **@internal** method, phpstan and psalm will report a bug/problem._" If the PSR submitter is correct in his descriptiojn of phpstan's and pslam's behavior and my interpretation of the **@internal** syntax is correct then bug reports should probably be opened against phpstan and psalm.

Thanks!

**Comment by jaapio** [comment]
The difference is:

`@internal marks a method as internal, which shall not be used by classes from another package/namespace` 

The inline variant `{@internal some notes}` is meant to filter parts of your documentation, for example, notes that are only for maintainers of your library. 

What other tools are doing with the specific formats is not written down in our docs. I know phpstan and psalm are using the tag to warn you about the use of internal methods. But will only do that for the `@interal` variant since they do no parse the description of a docblock.

**Comment by jaapio** [comment]
We added some extra examples, I hope this makes it more clear now
