### ISSUE TITLE
How to add/change the final url generated - Question

### ISSUE THREAD

**Issue by zebamba** [phpDocumentor/phpDocumentor#2847]
Is it possible to pass a value on the xml file to add to final url generated?
 
The uri generated looks like namespace/page.html 

I want to add a custom value like custom_value/namespace/page.html

**Comment by jaapio** [comment]
No it is not possible right now to change the urls in the generated html.

May I ask for what purpose you might want to do that?

**Comment by zebamba** [comment]
@jaapio 
The idea is to add the generated docs into a MVC documentation app, so a url will serve for example docs/php and another will serve docs/js.

Because the way the html urls are generated, once I added into the MVC app does not let me add the php to it.

It may be a okay feature to pass an optional parameter to be add before the url like the title is pass to the template.

What are your thoughts about it?

**Comment by jaapio** [comment]
Routing in phpDocumentor is quite a complex job. Since the output is static HTML. If you want to do something different I recommend you to give it a try to do some URL rewriting using `.htaccess` file or an equal format for you webserver. 

We cannot support this use-case since it would not be very common to do something like this.
