### ISSUE TITLE
Is anyone actually reading these issues?

### ISSUE THREAD

**Issue by Bill-ColeUS** [phpDocumentor/phpDocumentor#2881]
While this project seems alive, with some occasional commits, the github issues seem abandoned. Is anyone actually reading these, or should we not bother to write issues?

Thank you.

**Comment by ashnazg** [comment]
Given how much activity *does* happen on our Issues, particularly recently, I have to assume this one was opened by an AI/bot.

**Comment by mvriel** [comment]
Just in case, the Github issues are absolutely not abandoned; any feedback is very much appreciated. We are however a small team of people and do not always have the capacity to respond to every issue in a timely fashion. 

When I/we see something that we believe requires direct action we generally do so, and aside from the issues we have a separate roadmap with larger features that from time to time to precedence over the issues so that we can focus.

If anyone reading this is enthusiastic about helping out to reduce our issue count; I would very much appreciate that :)
