### ISSUE TITLE
Support for ARM docker container

### ISSUE THREAD

**Issue by lavanoid** [phpDocumentor/phpDocumentor#2927]
# Feature request

Hello. I am trying to run the docker container on my ODROID HC2, but running PHPDoc from the container gives me this error:
```
phpdoc run -d ./www/example.com/ -t ./docs/
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
```

Is it possible to have a docker container for ARM platforms?

**Comment by jaapio** [comment]
Hi

I don't think we will ever actively support ARM unless it becomes more common to have ARM architecture with php. It should be possible to build your own image using our phar release without too much knowledge about the internals of phpDocumentor. We would be happy to include such link into our readme as community provided 

I don't see how we could provide an official docker image with the current efforts our small team can provide.

**Comment by axel37** [comment]
Hi, just showing some interest for this as our current hosting environment (amazon web services) runs on arm VMs.

It would have been great to use the docker container (which we use for other parts of development) to run phpdoc instead of installing it on the vm, this would have made things more portable !

Thanks : )
