### ISSUE TITLE
Support raw directive for guides by default

### ISSUE THREAD

**Issue by daiwai** [phpDocumentor/phpDocumentor#3024]
It seems like raw directives are already parsed but are not passed through when the HTML is written.

```
.. raw:: html
    <u>underline</u>
```

It is possible to enable raw output by overriding the `code.html.twig` with something like:

```
{% if node.raw %}
    {{ node.value|raw }}
{% else %}
    <pre><code class="language-{{ node.language }} {{ node.startingLineNumber ? 'line-numbers' }}" {{ node.startingLineNumber ? 'data-start=' ~ node.startingLineNumber }}>{{ node.value }}</code></pre>
{% endif %}
```
I was wondering if this could be enabled by default or whether there is any reason not to?

**Comment by mvriel** [comment]
I have just fixed this on master; the next build of the docker container will include the changes and otherwise the next release of the phar file (not planned yet). You were absolutely pointing in the right direction; though ultimately it should not stay there. But that is a change for another time :) 

(just like the `:file:` option not being supported at the moment)
