### ISSUE TITLE
Clean template has bad links to navigate the structure

### ISSUE THREAD

**Issue by christianlupus** [phpDocumentor/phpDocumentor#3121]
# Template issue/request
Currently, the links in the generated document when using the `clean` template are not correctly generated. It seems there is a `../` missing in many of the relative ones.

## Steps to reproduce
1. Clone a repo `git clone --depth=1 git@github.com:phpDocumentor/phpDocumentor.git` for testing to a tmp location and cd into it.
2. Build the document (using docker here for sake of containment) 
```
docker run --rm -v $(pwd):/data --template clean -s graphs.enabled=true
```
3. Open the `build/website/docs/index.html` file in a browser.
4. Click on the `phpDocumentor` namespace
5. Look at the links in the page

## Expected behavior

The links are working.

## Actual behavior
In my example, I am visiting the file `file:///tmp/test-phpdoc/phpDocumentor/build/website/docs/namespaces/phpdocumentor.html`. When looking at the `Compiler` namespace, the link points to `namespaces/phpdocumentor-compiler.html` resulting in an absolute url of `file:///tmp/test-phpdoc/phpDocumentor/build/website/docs/namespaces/namespaces/phpdocumentor-compiler.html`.

Please note the doubled part in `/namespaces/namespaces/`. When removing this manually, the page can be accessed.

**Comment by christianlupus** [comment]
I just found #3089. This seems to be a similar problem.

Due to the docker setup, you could at most give absolute paths _within the container_. For any links outside this will not help as the path is most probably a different one.

**Comment by mvriel** [comment]
It has been some time since I last looked into this; at some point we switched to using the base tag in the head instead of trying to recalculate how many levels deep you are. Perhaps something there went wrong? We'd need to check our E2E tests as well, since this scenario should be covered

**Comment by ILL-DIE-TRYING** [comment]
Is there a time frame we can expect this to be fixed or is there a quick workaround that can be done to fix this issue in the generated files? I really do not like the default template at all and love the clean template. Also @source tags do not work still. How does a person include say the source for a function in the documentation? When clicking the source button next to a function usually goes to some unknown location in the file hundreds of lines away from the function you want to view. Is this REALLY the defacto standard for PHP documentation? Because HOLY COW. Also the documentation provided for V3 is spotty at best. I really need something like this, have spent hours writing doc blocks to find that it is like a half finished piece of software at best. I am literally two days into digging through the docs and such with no joy at all. Also, I tried the github markdown stuff and it does not act like it should at all.

**Comment by mvriel** [comment]
Thanks for the edit; it is much appreciated. As for a timeframe, I am afraid I am unable to provide one. 

@jaapio and I try to get as much done in our spare time, and at the moment mostly @jaapio, but truth be told: we would very much welcome any help that we can get with these types of issues. With the number of available hours, we try not only to fix bugs but also to maintain the various satellite packages, and to innovate and look forward.

So, if anything: this response is a plea for help from the community to aid in fixing these annoying bugs that may either be very small, or very big depending on what the actual cause is.

As for this issue; we have tried to solve relative paths by using the `<BASE>` HTML tag as that simplifies how we build a dependency graph and the locations of files. I am assuming here, that there is an erroneous assumption somewhere in the twig templates; but what both helps and doesn't help is that we are overhauling the Table Of Contents functionality that drives these links

**Comment by ILL-DIE-TRYING** [comment]
I forked and fixed the issue I believe. I have no way of testing.

**Comment by ILL-DIE-TRYING** [comment]
I'm not that capable with git to be honest but I *think* I have all the path stuff out of the template and somewhere you can see the changes I made.

Is there  way I could copy the clean template, rename it something else and enable it when using the .phar ? I couldn't catch on to how a custom template is actually put into the phar, sorry.

**Comment by jaapio** [comment]
@ILL-DIE-TRYING thanks for your attempts to fix this issue. I do really appreciate your efforts. 
To help you a bit more to debug and solve the issue you might want to try the following things. 

The path function in our templates is helping us to create the correct links. So the fix will not be to remove those. This will cause errors in other situations than yours. The issue here is that phpDocumentor renders static HTML. the paths rendered in the templates have to be related to the location of the element that is currently rendered. This means that we cannot simply render an URL to `/css/style.css` like you would do normally when your website is served by a webserver. 
Especially when people are using their local file system to visit the docs without any webserver this will break. 

That's why all URLs in the templates are prefixed with `../` or more levels up. 
To help the browser understand what is going on we have introduced a function `{{ renderBaseUrlHeader() }}` in phpDoc v3. This should always render the correct baseurl like you discovered in your second attempt. 

When fixing this issue you can do the following things to overwrite the templates used by phpdoc. 
create a directory `.phpdoc/template` in the root folder of your project. This project will contain the files you are overwriting during the run of phpdocumentor. 

Now we can copy the full layout.html.twig from the clean template into that directory. You can add any HTML to check things are working and the new layout.html.twig is used. I would recommend to add some kind of ugly H1 tag with a large debug message for example. 

If you have this setup working, which you can do with the phar you were using when reporting this issue, we can start changing the layout.html.twig. I would start with the earlier mentioned function. 
You might want to check this file: https://github.com/phpDocumentor/phpDocumentor/blob/master/data/templates/default/layout.html.twig#L10 for reference. 

You can also check our repo for more details about overwriting templates. like we did here. https://github.com/phpDocumentor/phpDocumentor/tree/master/.phpdoc/template

Please let me know if you have any questions or problems I'm here to help you.

**Comment by jaapio** [comment]
FYI: I assigned this ticket to you, so I know you are working on this. This doesn't mean that you have to fix it in any way. But like I said before your PR's are very welcome!

**Comment by ILL-DIE-TRYING** [comment]
Okay so the only change needed to get the links working was your suggestion of adding {{ renderBaseUrlHeader() }} to layout.html.twig . THANK YOU!

For anyone that needs to know:

In your directory where your generate docs are placed, create a .phpdoc directory. If it is already there, just browse into it. Create a directory there called "template". 

Grab a copy of layout.html.twig from https://github.com/phpDocumentor/phpDocumentor/blob/master/data/templates/clean/layout.html.twig

Place the layout.html.twig file in the newly created template directory.

Edit layout.html.twig to match this section at the top (sorry I don't know markup):

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
	{{ renderBaseUrlHeader() }}

Save the file and rerun phpdoc.

Done!

I do see this template needs to be modernized for V3. I wish I had the time to do it but I just spent a day trying to figure this out when I should be working on my project I am being paid for. 🤪 

I did notice in the modal source view no line numbers are showing and the map generation seems as though it isn't working, just so you know.

THANKS AGAIN!

If I come up with some free time maybe I can dig deeper into this stuff. The code is pretty advanced and I will definitely be dumb and slow but, HEY I may be able to help out somehow on some low hanging fruit.
