### ISSUE TITLE
null in @params

### ISSUE THREAD

**Issue by Misosooup** [phpDocumentor/phpDocumentor#3242]
Hi all, this is such a small matter that I am very embarrassed to even post this up. However, this has become a big hoohaa in the company I am working for at the moment.

As per your documentation, `null` is a valid primitive type but the docs specifically stated "usually" used in `@return` which makes some of my team mates think that is "ONLY" used in `@return`.

I did a quick search on the code base to see if it's being used in `@param` and surely it is. 

On a quick search, there are some post on stackoverflow encountering the same issue.
https://stackoverflow.com/questions/49073384/optional-nullable-parameters-in-phpdoc.

Can the docs be updated to reflect that it is valid to use `null` in `@param` to denote an optional field?

**Comment by mvriel** [comment]
Any type reference, including the `@param` tag's type reference, matches the rules described in https://docs.phpdoc.org/guide/references/phpdoc/types.html. This includes number 10, the use of `null`.

> Can the docs be updated to reflect that it is valid to use null in @param to denote an optional field?

Unfortunately, this would add more confusion than it would resolve. At least in my opinion. Because a field may be omitted when calling a method or function and then its _default_ value would be used. But this value need not be `null` but any simple type. As such, adding null does not mean that a field is optional.

if your team mates still are in doubt, please refer them to the page https://docs.phpdoc.org/guide/references/phpdoc/tags/param.html#param and click through on types to get a thorough description :)
