### ISSUE TITLE
Some source code popups do not work

### ISSUE THREAD

**Issue by smileBeda** [phpDocumentor/phpDocumentor#3271]
In some cases, not sure why, source code popup does nothing when clicked.

## Expected behavior
Source code working always.

## Actual behavior
Source code popup does not always open

## Steps to reproduce the problem

I created doc with `--sourcecode` set and uploaded it to a server. Mostly it works (apart of #3270), but I just noticed, sometimes the source code simply does not work. The popup will not open.

To see the issue, please head to [this page](https://www.docs.tukutoi.com/packages/TukuToi-CPDirectoryIntegration.html) and click on any of the `<>` on this page.
None will work.
Now head to [this page](https://www.docs.tukutoi.com/classes/Cp-Plgn-Drctry-Admin.html) or any other, and all `<>` will work

**Comment by mvriel** [comment]
I think I found the issue; it is actually two-fold:

1. The include for the source-modal.html.twig is missing in the namespace, package and file base templates.
2. The include doesn't work in the namespace and package context because it assumes that the file associated with the current node is your target source path; this is not true for namespaces and classes because they are collections.

The first is easily fixed; the second needs some rework as the source file that you want to see should be provided to the source modal instead of the source modal pulling it from the root template

**Comment by mvriel** [comment]
Hmm, bugger. Found another annoying issue. If you click on view source it will do a request for each element on the page. Thus making many duplicate requests. Don't know how I missed that during the initial implementation 😅

**Comment by mvriel** [comment]
Will be fixed by PR https://github.com/phpDocumentor/phpDocumentor/pull/3284; and I have improved the way it deals with the whole `file://` situation. It will not render the buttons that open it when displayed locally and a warning is emitted in the console.

@smileBeda if you have made custom changes to your template; you may want to check whether this didn't break anything related to your local changes.
