### ISSUE TITLE
@api tag dont work in default template?

### ISSUE THREAD

**Issue by x2ADLcRoo33ZygUA** [phpDocumentor/phpDocumentor#3337]
- **phpDocumentor version:** 3.3.1 (phar)
- **template:** default
- **test php file:**
```
<?php
class Test {
	/**
	 * @api
	 * @foo
	 */
	public function method () {

	}
}
```
- **cli run command:** `php phpDocumentor.phar -d . -t result`
- **what i get:**
![image](https://user-images.githubusercontent.com/55540747/195698465-766f6028-b259-4258-b356-b93b6913e58b.png)
- **what i expect:** Any note that would indicate an @api.

> Not all templates may show the API sidebar section. If your project uses the @api tag, it is recommended to verify your preferred [template](https://phpdoc.org/templates) supports the API sidebar before generating the documentation.

These words from the documentation hint to me that @api tag does not work due to the template. But does it not seem very stupid to you that the @api tag is not maintained even at the level that supports custom tags (like @foo)?

**Comment by mvriel** [comment]
The API tag is explicitly excluded from the rendering of the tag blocks because the intention is/was to display that in a different way. Apparently, that was not done and as such it was never shown. I have now created PR https://github.com/phpDocumentor/phpDocumentor/pull/3392 to display a label with a method to indicate whether it has the `@api` tag
