### ISSUE TITLE
Installation with synology docker

### ISSUE THREAD

**Issue by Ghost108** [phpDocumentor/phpDocumentor#3345]
Hi,

I would like to install the docker version of phpDocumentor on my synology nas.

On terminal I tried:
`docker run --rm -v /volume1/docker/phpDocumentor:/data phpdoc/phpdoc`

Result:

```
Unable to find image 'phpdoc/phpdoc:latest' locally
latest: Pulling from phpdoc/phpdoc
bd159e379b3b: Pull complete
1e83b070fd97: Pull complete
e7793be89e9c: Pull complete
4220e0c03377: Pull complete
2eec08d1f85c: Pull complete
fad376bef81f: Pull complete
2eafa146ecd9: Pull complete
682415762cb7: Pull complete
bfac10460799: Pull complete
76d341c20979: Pull complete
dcef3ed72d52: Pull complete
34a69b8d93df: Pull complete
da1ea6b3d10a: Pull complete
Digest: sha256:69c786ec8238dc0e6adf3e6211eb82516cff339b064dfaaee79ed8824b01cb25
Status: Downloaded newer image for phpdoc/phpdoc:latest
phpDocumentor dev-master@144702e

Parsing files

Applying transformations (can take a while)

  1/21 [=>--------------------------]   4%
 11/21 [==============>-------------]  52%
 17/21 [======================>-----]  80%
 21/21 [============================] 100%
All done in 0 seconds!
```

Looks good. I see also file in my phpDocumentor folder.
But I see no phpdoc container and if I am using the command "phpdoc" in terminal:

-> phpdoc: command not found

Where is my mistake?

**Comment by mvriel** [comment]
@Ghost108 Are you expecting a continuously running container? Because phpDocumentor is built as a utility container using the ENTRYPOINT feature of Docker. This means that it will run for the duration that it takes phpDocumentor to execute and then stop. 

If you were expecting a webserver -just guessing here-, phpDocumentor is built to generate a static site that can be served by any webserver. In this case, you would need to start a docker image by Apache, Nginx or any other and volume map the results from the phpDocumentor run into that.

Does this answer your question?

**Comment by jaapio** [comment]
Stale not response for months.
