### ISSUE TITLE
Find undocumented "throws"

### ISSUE THREAD

**Issue by KingCrunch** [phpDocumentor/phpDocumentor#361]
Must say: Don't know, how it works exactly ;) But if the parser can find `throws` it should try to find the corresponding `@throws` tag and either mark it errornous, or add the statement itself. It would be cool, if functions/methods would be treated the same way, when they call a "throwing" function/method and don't catch it, but I can imagine, this can become very complex.

**Comment by DannyvdSluijs** [comment]
Mike any progress on this or can I help ?

**Comment by mvriel** [comment]
Hello @DannyvdSluijs, since 2012 things have changed incredibly (can't believe this has been open for so long :)). In the Reflection package we use PHP-Parser to read the source code and currently does not perform validations on lines of code versus DocBlocks; without diving into this I don't know how to resolve this currently.
