### ISSUE TITLE
oddity the file phpdoc.dist.xml

### ISSUE THREAD

**Issue by rino1** [phpDocumentor/phpDocumentor#3838]
An example of the file phpdoc.dist.xml is shown on the page https://docs.phpdoc.org/guide/references/configuration.html

I want to focus on the following lines

```
    <paths>
        <output>build/api</output>
        <cache>build/cache</cache>
    </paths>
```
    
In detail

```
        <output>build/api</output>
```

Why **build/api**?
Usually, the files that make up the documentation should not be found in the **docs** directory?

**Comment by jaapio** [comment]
phpDocumentor started as a documentation tool to automatically generate so-called api docs out of docblocks. Back then it was quite common to have a docs directory called docs, and an api documentation containing the listing of all classes and functions. 

The examples are from that time and never adjusted. 

I would welcome any improvements on our docs. Which can be found in the docs Directory in this repository😅.

**Comment by rino1** [comment]
> phpDocumentor started as a documentation tool to automatically generate so-called api docs out of docblocks. Back then it was quite common to have a docs directory called docs, and an api documentation containing the listing of all classes and functions.

mmmhhh...
I don't understand.
Could you explain better?
 
> The examples are from that time and never adjusted.
> 
> I would welcome any improvements on our docs. Which can be found in the docs Directory in this repository😅.

As mentioned, if you don't express yourself clearly, things become very difficult.

**Comment by jaapio** [comment]
It sounds to me like you are pretty new to the whole concept of phpDocumentor. I'm not going to explain everything in detail. Some self research is definitely required. But I will give it another try.

The output directory is just an example. There is no need to follow the example. If you want to use docs. Feel free to do so. 

## api docs

Api, or in a long application programming interface. Is in our context the interface of a class or function in a code base. It describes the parameters that you can pass to a function or class. 

`function sum($a, $b)` is an example of an api. But just from this notation I don't know what a and b are. So that needs documentation. This documentation is written in docblocks. See our website for a better description of docblocks. 
https://docs.phpdoc.org/guide/getting-started/what-is-a-docblock.html#what-is-a-docblock

phpDocumentor can collect all these functions and classes in a project and generates an html website which is easier to read and to search. 

An example is our own website: https://docs.phpdoc.org/classes/phpDocumentor-Configuration-ConfigurationFactory.html

## maintenance

phpDocumentor is mostly maintained by me. I do this in my spare time next to my fulltime job. Which means that I'm now typing this message for free. Nobody is paying me to do so. Nor this is a support portal where you can just request help or expect me to answer all your questions. Some of the issues should be solved by you. If you think I'm not expressing myself correctly, and make things too complex, the best solution is to give it a try. The documentation might help in this, but as I'm obviously biased about the whole topic, I might not be the right person to help a beginner. That's why I requested you to contribute to the docs. 

Having that said, I completely get that phpDocumentor is a complex tool. Which solves a complex problem. Without any background, or additional information I'm not able to really answer your questions. Based on your GitHub profile you do not have any experience. So I do not know your level of knowledge. Which makes support very hard. There is much difference between explaining a child of 4 the concept of phpDocumentor vs a veteran with 30 years of development experience.

**Comment by rino1** [comment]
> The output directory is just an example. There is no need to follow the example. If you want to use docs. Feel free to do so.

OK
 
> ## api docs
> Api, or in a long application programming interface. Is in our context the interface of a class or function in a code base. It describes the parameters that you can pass to a function or class.
> 
> `function sum($a, $b)` is an example of an api. But just from this notation I don't know what a and b are. So that needs documentation. This documentation is written in docblocks. See our website for a better description of docblocks. https://docs.phpdoc.org/guide/getting-started/what-is-a-docblock.html#what-is-a-docblock
> 
> phpDocumentor can collect all these functions and classes in a project and generates an html website which is easier to read and to search.
> 
> An example is our own website: https://docs.phpdoc.org/classes/phpDocumentor-Configuration-ConfigurationFactory.html
> 
> ## maintenance
> phpDocumentor is mostly maintained by me. I do this in my spare time next to my fulltime job. Which means that I'm now typing this message for free. Nobody is paying me to do so. Nor this is a support portal where you can just request help or expect me to answer all your questions. Some of the issues should be solved by you. If you think I'm not expressing myself correctly, and make things too complex, the best solution is to give it a try.

But in the specific case I don't think there is much to try: what did I ask in the initial post?

However my problem is that I don't speak English, but, in any case, now you have explained yourself much better, and in any case I have been using phpdocumentor for years.

Allow me only one last clarification

>  Back then it was quite common to have a docs directory called docs,

OK

> and an api documentation containing the listing of all classes and functions.

Meaning what?
