### ISSUE TITLE
{@inheritdoc} not working as expected with interfaces

### ISSUE THREAD

**Issue by robocoder** [phpDocumentor/phpDocumentor#389]
2.0.0a1:  In my phpdoc.dist.xml, I added the Symfony2 and Doctrine source directories.  In the generated docs, I can see my subclasses have inherited methods from the Sf2/Doctrine parent classes, but methods that I've tagged with {@inheritdoc} remain (unconverted)

I'm expecting to see the equivalent of copy/pasting the parent method's description, @param, @return, etc.

Are my expectations wrong?

**Comment by venimus** [comment]
According https://www.phpdoc.org/docs/latest/guides/inheritance.html#properties
```
/**
 * {@inheritDoc}
 */
```
should not work as expected and should result to a plain text ` {@inheritDoc}` as short description. In this construction the tag is on the first line, it is taken for short description because it does not start with `@`. However inline tags are not allowed/parsed in short descriptions and are taken as plain text.
