### ISSUE TITLE
Global __NAMESPACE__ not interpreted properly

### ISSUE THREAD

**Issue by johnlet** [phpDocumentor/phpDocumentor#512]
Using version 2.0.0a6
This demonstrates the problem...

<pre>
<?php
/**
 * Demonstrates the bug handling NAMESPACE variable
 *
 * @author John Letourneau <topgun@bell-labs.com>
 */
namespace com\btl {
/**
 * This is documented, but is in the global scope
 */
define( 'A_CONSTANT', 'My string' );

/**
 * This causes the problem.
 *
 * We want the constant to be in the namespace, but the parser is not
 * interpreting this properly.
 */
define( __NAMESPACE__ . 'B_CONSTANT', 25 );

/**
 * This works OK.
 */
class AClass {
  /**
   * The a parameter
   */
  var $aparam;
}

}

?>
</pre>

**Comment by mvriel** [comment]
In phpDocumentor 3.0 I had expected this to be fixed; so I went to revisit this issue. To my horror, this is still an issue and in the current release Define is not parsed at all due to a bug. I have fixed this on master; but there is an upstream issue (https://github.com/phpDocumentor/Reflection/issues/182) that needs to be addressed too before I can resolve this issue. To be continued

**Comment by jaapio** [comment]
I fixed this issue in my last commit, it will be part of the next v3.4 release.
