### ISSUE TITLE
Include a searcher for classes/methods/properties

### ISSUE THREAD

**Issue by dcastanos** [phpDocumentor/phpDocumentor#636]
It would be nice to have a searcher (with autocomplete) to quickly find classes/methods/properties.

**Comment by mvriel** [comment]
This feature is planned to be included into phpDocumentor 3.0. 

I have been reviewing several options including lunr.js and elasticlunr.js but the biggest issue so far is that client-side building of the FTS index requires Node.js. This is a requirement that is hard to sell (imo) and building the index client side requires a large JSON element that needs to be included in every page load; making for terrible performance.

I am now reviewing https://github.com/cebe/js-search by @cebe to check whether that fulfills the requirements that we have for search. The advantage of this package is that the index is pre-rendered in PHP, the most interesting part here is performance on a codebase the size of Zend Framework or Symfony and how large the index becomes since it needs to be included on each page load. (AJAX loading cannot be supported since offline browsing doesn't do AJAX requests; though this may be circumvented using JSONP)

**Comment by cebe** [comment]
Thanks for mentioning me. Note that this thing is in experimental state and might need some improvement. It currently also does not work on the basis of classes or property/method names but does some full text search things on the HTML which has simply stripped the tags.

The current index size for Yii framework docs is about 450KB (gzipped) http://www.yiiframework.com/doc-2.0/jssearch.index.js

When you are only interested in searching classes or methods the size of the index can be reduced much more. There is some code I wrote for the rewrite of the yiiframework.com website which we are currently working on: https://github.com/yiisoft-contrib/yiiframework.com/blob/837e4ae8d24c02283cca45158ae68f087f39b35d/js/search.js

This uses an index of classes: http://yiiframework.domain-na.me/doc/api?_format=json
And one for method and property names: http://yiiframework.domain-na.me/doc/api/class-members?_format=json

Also note that if you load the search index as JS files, they will be loaded on first use and afterwards are stored by browser cache until they expire.

**Comment by mvriel** [comment]
phpDocumentor 3 now includes full search capabilities, even on localhost. This is provided in the new default template. At this point, I am not backporting it to the other templates to be able to focus on other features. If there is enough interest we may do so, it would even be better if someone else could reuse the code we wrote for the new default template and submits a PR
