### ISSUE TITLE
Constants documentation not used

### ISSUE THREAD

**Issue by NumEricR** [phpDocumentor/phpDocumentor#817]
Hi,

I wanted to document some constants but the output doesn't show my comments.
I use phpDocumentor v2.0.0a12 with that piece of code:

```
<?php

/**
 * Description 1.
 */
define('CONSTANT1', 'constant_1');
/**
 * @var string Description 2
 */
define('CONSTANT2', 'constant_2');
```

```
phpdoc -f /Users/User/Desktop/test/test.php -t /Users/User/Desktop/test/build/api/'
```

```
Initializing parser and collecting files .. OK
Parsing files
Parsing /Users/User/Desktop/test/test.php
  No page-level DocBlock was found in file test.php
Storing structure.xml in "/Users/User/Desktop/test/build/api/structure.xml" .. OK
Initializing transformer .. OK
Processing behaviours .. OK
Executing transformations
```

And here's the display I get:

![phpdocumentor_constants](https://f.cloud.github.com/assets/262560/471575/64733f26-b71d-11e2-9369-bcffa2139e4c.png)

**Comment by fi5er** [comment]
I can confirm that the second version (using `@var string`) does not work in 2.8.5 with the "clean" template.

With the "responsive" template, the doc block text does show up, but is surrounded by `&lt;p&gt;` .. `&lt;/p&gt;` (that is, not `<p>` tags, but escaped HTML visible on the page).

It would be useful to support `@var {type} {description}` for constants, because the type is not necessarily known to phpDocumentor; for example:

    define("BLARG", getBlargValue());

**Comment by jaapio** [comment]
This was fixed at some point during the development of v3.
