### ISSUE TITLE
Interactive API explorer inside documentation

### ISSUE THREAD

**Issue by Zyles** [phpDocumentor/phpDocumentor#823]
Is it possible to use phpdoc to create documentation for a public rest API and integrate an interactive API explorer in the style of Swagger?

I don't really want to document the entire PHP-application to the public. Rather the API endpoints, parameters etc. But Swagger only seems to support the API explorer and I want something that has both.

Something like the Campaign Monitor API documentation with Swagger in it... something like this: http://dev.tendrilinc.com/docs/account_information

**Comment by mvriel** [comment]
This issue is more than 7 years old; and although I do like the suggestion a lot, I feel obligated to close this as I do not see us fulfilling this request on short notice.

With the release of phpDocumentor 3.0, we have big plans in terms of future support of more types of documentation; including OpenAPI. Though our focus is currently on hand-written documentation using RestructuredText and I just do not know when we will get around to this.
