### ISSUE TITLE
In depth Closure definitions.

### ISSUE THREAD

**Issue by eborden** [phpDocumentor/phpDocumentor#830]
Doc blocks do not currently support in depth Closure definitions. Only a shallow definition is possible with the type definition:

``` php
/*
 * @return Closure [<description>]
 */
```

Use of closures is becoming more prevalent in modern PHP, so a more in depth format is needed.
## Some possible formats

Single line definition. Double brackets are used to denote a sub definition.

``` php
/* 
 * @return Closure [[@param [type] [name] [<description>]; @return [type] [<description>]; ...]]
 */
```

Inner doc block definition. Ending comment statement is excluded on the inner doc block.

``` php
/*
 * @return Closure /* @param [type] [name] [<description>]
 *                  * @return [type] [<description>]
 *                  * ...
 */
```

**Comment by iluuu1994** [comment]
Is this still being considered? 
The proposed syntax looks a little bloated. Swift has pretty syntax for closures:

```Swift
(Type1, Type2) -> ReturnType
```

For PHP it would probably make more sense to use the `:` symbol for the return type to be consistent with function return types:

```PHP
/**
 * @param (Type1, Type2): ReturnType $callback
 */
```

I could see how this would be difficult to implement for ambiguity reasons though.

**Comment by sl1331** [comment]
Or how about:
@param callable(string, int):array $mycallback my description
?
callable simply identifies that it is a closure or similar, the parenthesis contain standard parameter types (including allowing ...args), and the colon:type defines the return type (can be or'd as well). The rest of the line is standard parameter definition.

JSDoc (and Google Closure) use something similar except in curly braces

@param {function(string, number):boolean} mycallback my description

I'd just like to get my IDE to stop giving me warnings for unrecognized properties and methods because it doesn't know what the parameters of the callable function are.

**Comment by renekoch** [comment]
Is this still in consideration? This has long been a wish of mine. Any syntax will do, tho @iluuu1994 / @sl1331 suggestion seems sane in a PHP context.

**Comment by jaapio** [comment]
Yes it is, but most likelly it will be implemented in phpdocumentor v3. If someone is able to create a pr for this that might speed up the progres.

**Comment by the-liquid-metal** [comment]
Sorry if out of topic.
Rather than there is no solution, i have created my own sollution. This is simple, common sense, and without introduce new syntax:
https://stackoverflow.com/questions/16589902/syntax-of-closure-in-phpdoc/51208203#51208203

Of course permanent solution (with new syntax) is absolutely better.
